apiVersion: v1
kind: Pod
metadata:
  name: lcls-cu-injector-ml-pod
  labels:
    app: lcls-cu-injector-ml-pod
spec:
  containers:
  - name: lcls-cu-injector-ml-pod
    image: scr.svc.stanford.edu/gopikab/lcls-cu-injector-ml:0.4
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
